export const paises = [
    "Afganistán",
    "Alemania",
    "Argentina",
    "Australia",
    "Bolivia",
    "Brasil",
    "Canadá",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dinamarca",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "España",
    "Estados Unidos",
    "Francia",
    "Guatemala",
    "Honduras",
    "India",
    "Italia",
    "Japón",
    "México",
    "Nicaragua",
    "Panamá",
    "Paraguay",
    "Perú",
    "Portugal",
    "Reino Unido",
    "República Dominicana",
    "Rusia",
    "Sudáfrica",
    "Uruguay",
    "Venezuela",
    "Otro"
  ];